# This file was automagically generated by mbed.org. For more information, 
# see http://mbed.org/handbook/Exporting-to-GCC-ARM-Embedded

APP_DIR := apps
LIB_DIR := lib
CONFIG_DIR := config


###############################################################################
# Boiler-plate

# cross-platform directory manipulation
ifeq ($(shell echo $$OS),$$OS)
    MAKEDIR = if not exist "$(1)" mkdir "$(1)"
    RM = rmdir /S /Q "$(1)"
else
    MAKEDIR = '$(SHELL)' -c "mkdir -p \"$(1)\""
    RM = '$(SHELL)' -c "rm -rf \"$(1)\""
endif

OBJDIR := build
# Move to the build directory
ifeq (,$(filter $(OBJDIR),$(notdir $(CURDIR))))
.SUFFIXES:
mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
MAKETARGET = '$(MAKE)' --no-print-directory -C $(OBJDIR) -f '$(mkfile_path)' \
		'SRCDIR=$(CURDIR)' $(MAKECMDGOALS)
.PHONY: $(OBJDIR) clean
all:
	+@$(call MAKEDIR,$(OBJDIR))
	+@$(MAKETARGET)
$(OBJDIR): all
Makefile : ;
% :: $(OBJDIR) ; :
clean :
	$(call RM,$(OBJDIR))

else

# trick rules into thinking we are in the root, when we are in the bulid dir
VPATH = ..

# Boiler-plate
###############################################################################
# Project settings

PROJECT := mbed_blinky


# Project settings
###############################################################################
# Objects and Paths

OBJECTS += test/blinky/main.o

 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/PeripheralPins.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/analogin_api.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/analogin_device.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/analogout_api.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/analogout_device.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/can_api.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/cmsis_nvic.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/flash_api.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/gpio_api.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/gpio_irq_api.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/gpio_irq_device.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/hal_tick_overrides.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/i2c_api.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/lp_ticker.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/mbed_board.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/mbed_crc_api.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/mbed_overrides.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/mbed_retarget.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/mbed_sdk_boot.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/mbed_tz_context.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/pinmap.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/port_api.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/pwmout_api.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/pwmout_device.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/rtc_api.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/serial_api.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/serial_device.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/sleep.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/spi_api.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/startup_stm32f091xc.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_adc.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_adc_ex.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_can.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_cec.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_comp.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_cortex.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_crc.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_crc_ex.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_dac.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_dac_ex.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_dma.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_flash.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_flash_ex.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_gpio.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_i2c.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_i2c_ex.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_i2s.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_irda.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_iwdg.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_pcd.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_pcd_ex.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_pwr.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_pwr_ex.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_rcc.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_rcc_ex.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_rtc.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_rtc_ex.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_smartcard.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_smartcard_ex.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_smbus.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_spi.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_spi_ex.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_tim.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_tim_ex.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_tsc.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_uart.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_uart_ex.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_usart.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_hal_wwdg.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_ll_adc.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_ll_comp.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_ll_crc.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_ll_crs.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_ll_dac.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_ll_dma.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_ll_exti.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_ll_gpio.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_ll_i2c.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_ll_pwr.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_ll_rcc.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_ll_rtc.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_ll_spi.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_ll_tim.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_ll_usart.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm32f0xx_ll_utils.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/stm_spi_api.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/system_clock.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/system_stm32f0xx.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/trng_api.o
 SYS_OBJECTS += $(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/us_ticker.o

INCLUDE_PATHS += -I../$(CONFIG_DIR)/.
INCLUDE_PATHS += -I../$(LIB_DIR)/.
INCLUDE_PATHS += -I../$(LIB_DIR)/mbed
INCLUDE_PATHS += -I../$(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC
INCLUDE_PATHS += -I../$(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TARGET_STM
INCLUDE_PATHS += -I../$(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TARGET_STM/TARGET_STM32F0
INCLUDE_PATHS += -I../$(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F091RC
INCLUDE_PATHS += -I../$(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F091RC/device
INCLUDE_PATHS += -I../$(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TARGET_STM/TARGET_STM32F0/device
INCLUDE_PATHS += -I../$(LIB_DIR)/mbed/drivers
INCLUDE_PATHS += -I../$(LIB_DIR)/mbed/hal
INCLUDE_PATHS += -I../$(LIB_DIR)/mbed/platform

LIBRARY_PATHS := -L../$(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM 
LIBRARIES := -lmbed 
LINKER_SCRIPT ?= ../$(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TOOLCHAIN_GCC_ARM/STM32F091XC.ld

# Objects and Paths
###############################################################################
# Tools and Flags

AS      = arm-none-eabi-gcc
CC      = arm-none-eabi-gcc
CPP     = arm-none-eabi-g++
LD      = arm-none-eabi-gcc
ELF2BIN = arm-none-eabi-objcopy
PREPROC = arm-none-eabi-cpp -E -P -Wl,--gc-sections -Wl,--wrap,main -Wl,--wrap,_malloc_r -Wl,--wrap,_free_r -Wl,--wrap,_realloc_r -Wl,--wrap,_memalign_r -Wl,--wrap,_calloc_r -Wl,--wrap,exit -Wl,--wrap,atexit -Wl,-n -mcpu=cortex-m0 -mthumb


C_FLAGS += -std=gnu99
C_FLAGS += -include
C_FLAGS += ../../$(CONFIG_DIR)/mbed_config.h
C_FLAGS += -DROVERBOARD_COMMON_PINMAP
C_FLAGS += -D__CORTEX_M0
C_FLAGS += -DMBED_BUILD_TIMESTAMP=1548889013.95
C_FLAGS += -DCMSIS_VECTAB_VIRTUAL
C_FLAGS += -D__MBED__=1
C_FLAGS += -DDEVICE_I2CSLAVE=1
C_FLAGS += -DTARGET_LIKE_MBED
C_FLAGS += -DDEVICE_PORTOUT=1
C_FLAGS += -DDEVICE_PORTINOUT=1
C_FLAGS += -D__MBED_CMSIS_RTOS_CM
C_FLAGS += -DTARGET_STM32F0
C_FLAGS += -DDEVICE_RTC=1
C_FLAGS += -DDEVICE_SERIAL_ASYNCH=1
C_FLAGS += -D__CMSIS_RTOS
C_FLAGS += -DTOOLCHAIN_GCC
C_FLAGS += -DDEVICE_CAN=1
C_FLAGS += -DTARGET_CORTEX_M
C_FLAGS += -DDEVICE_I2C_ASYNCH=1
C_FLAGS += -DARM_MATH_CM0
C_FLAGS += -DDEVICE_ANALOGOUT=1
C_FLAGS += -DTARGET_M0
C_FLAGS += -DTARGET_NUCLEO_F091RC
C_FLAGS += -DDEVICE_SPI_ASYNCH=1
C_FLAGS += -DDEVICE_LPTICKER=1
C_FLAGS += -DDEVICE_PWMOUT=1
C_FLAGS += -DDEVICE_INTERRUPTIN=1
C_FLAGS += -DTARGET_CORTEX
C_FLAGS += -DDEVICE_I2C=1
C_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=2
C_FLAGS += -DDEVICE_STDIO_MESSAGES=1
C_FLAGS += -DTARGET_FF_MORPHO
C_FLAGS += -DTARGET_FAMILY_STM32
C_FLAGS += -DTARGET_FF_ARDUINO
C_FLAGS += -DTARGET_RELEASE
C_FLAGS += -DTARGET_STM
C_FLAGS += -DDEVICE_SERIAL_FC=1
C_FLAGS += -DDEVICE_USTICKER=1
C_FLAGS += -DDEVICE_PORTIN=1
C_FLAGS += -DDEVICE_SLEEP=1
C_FLAGS += -DTOOLCHAIN_GCC_ARM
C_FLAGS += -DDEVICE_CRC=1
C_FLAGS += -DDEVICE_SPI=1
C_FLAGS += -DCMSIS_VECTAB_VIRTUAL_HEADER_FILE=\"cmsis_nvic.h\"
C_FLAGS += -DDEVICE_SPISLAVE=1
C_FLAGS += -DDEVICE_ANALOGIN=1
C_FLAGS += -DDEVICE_SERIAL=1
C_FLAGS += -DTARGET_STM32F091RC
C_FLAGS += -DDEVICE_FLASH=1
C_FLAGS += -DTARGET_LIKE_CORTEX_M0
C_FLAGS += -include
C_FLAGS += ../../$(CONFIG_DIR)/mbed_config.h
C_FLAGS += -std=gnu99
C_FLAGS += -c
C_FLAGS += -Wall
C_FLAGS += -Wextra
C_FLAGS += -Wno-unused-parameter
C_FLAGS += -Wno-missing-field-initializers
C_FLAGS += -fmessage-length=0
C_FLAGS += -fno-exceptions
C_FLAGS += -fno-builtin
C_FLAGS += -ffunction-sections
C_FLAGS += -fdata-sections
C_FLAGS += -funsigned-char
C_FLAGS += -MMD
C_FLAGS += -fno-delete-null-pointer-checks
C_FLAGS += -fomit-frame-pointer
C_FLAGS += -Os
C_FLAGS += -g1
C_FLAGS += -mcpu=cortex-m0
C_FLAGS += -mthumb

CXX_FLAGS += -std=gnu++98
CXX_FLAGS += -fno-rtti
CXX_FLAGS += -Wvla
CXX_FLAGS += -include
CXX_FLAGS += ../../$(CONFIG_DIR)/mbed_config.h
CXX_FLAGS += -DROVERBOARD_COMMON_PINMAP
CXX_FLAGS += -D__CORTEX_M0
CXX_FLAGS += -DMBED_BUILD_TIMESTAMP=1548889013.95
CXX_FLAGS += -DCMSIS_VECTAB_VIRTUAL
CXX_FLAGS += -D__MBED__=1
CXX_FLAGS += -DDEVICE_I2CSLAVE=1
CXX_FLAGS += -DTARGET_LIKE_MBED
CXX_FLAGS += -DDEVICE_PORTOUT=1
CXX_FLAGS += -DDEVICE_PORTINOUT=1
CXX_FLAGS += -D__MBED_CMSIS_RTOS_CM
CXX_FLAGS += -DTARGET_STM32F0
CXX_FLAGS += -DDEVICE_RTC=1
CXX_FLAGS += -DDEVICE_SERIAL_ASYNCH=1
CXX_FLAGS += -D__CMSIS_RTOS
CXX_FLAGS += -DTOOLCHAIN_GCC
CXX_FLAGS += -DDEVICE_CAN=1
CXX_FLAGS += -DTARGET_CORTEX_M
CXX_FLAGS += -DDEVICE_I2C_ASYNCH=1
CXX_FLAGS += -DARM_MATH_CM0
CXX_FLAGS += -DDEVICE_ANALOGOUT=1
CXX_FLAGS += -DTARGET_M0
CXX_FLAGS += -DTARGET_NUCLEO_F091RC
CXX_FLAGS += -DDEVICE_SPI_ASYNCH=1
CXX_FLAGS += -DDEVICE_LPTICKER=1
CXX_FLAGS += -DDEVICE_PWMOUT=1
CXX_FLAGS += -DDEVICE_INTERRUPTIN=1
CXX_FLAGS += -DTARGET_CORTEX
CXX_FLAGS += -DDEVICE_I2C=1
CXX_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=2
CXX_FLAGS += -DDEVICE_STDIO_MESSAGES=1
CXX_FLAGS += -DTARGET_FF_MORPHO
CXX_FLAGS += -DTARGET_FAMILY_STM32
CXX_FLAGS += -DTARGET_FF_ARDUINO
CXX_FLAGS += -DTARGET_RELEASE
CXX_FLAGS += -DTARGET_STM
CXX_FLAGS += -DDEVICE_SERIAL_FC=1
CXX_FLAGS += -DDEVICE_USTICKER=1
CXX_FLAGS += -DDEVICE_PORTIN=1
CXX_FLAGS += -DDEVICE_SLEEP=1
CXX_FLAGS += -DTOOLCHAIN_GCC_ARM
CXX_FLAGS += -DDEVICE_CRC=1
CXX_FLAGS += -DDEVICE_SPI=1
CXX_FLAGS += -DCMSIS_VECTAB_VIRTUAL_HEADER_FILE=\"cmsis_nvic.h\"
CXX_FLAGS += -DDEVICE_SPISLAVE=1
CXX_FLAGS += -DDEVICE_ANALOGIN=1
CXX_FLAGS += -DDEVICE_SERIAL=1
CXX_FLAGS += -DTARGET_STM32F091RC
CXX_FLAGS += -DDEVICE_FLASH=1
CXX_FLAGS += -DTARGET_LIKE_CORTEX_M0
CXX_FLAGS += -include
CXX_FLAGS += ../../$(CONFIG_DIR)/mbed_config.h
CXX_FLAGS += -std=gnu++98
CXX_FLAGS += -fno-rtti
CXX_FLAGS += -Wvla
CXX_FLAGS += -c
CXX_FLAGS += -Wall
CXX_FLAGS += -Wextra
CXX_FLAGS += -Wno-unused-parameter
CXX_FLAGS += -Wno-missing-field-initializers
CXX_FLAGS += -fmessage-length=0
CXX_FLAGS += -fno-exceptions
CXX_FLAGS += -fno-builtin
CXX_FLAGS += -ffunction-sections
CXX_FLAGS += -fdata-sections
CXX_FLAGS += -funsigned-char
CXX_FLAGS += -MMD
CXX_FLAGS += -fno-delete-null-pointer-checks
CXX_FLAGS += -fomit-frame-pointer
CXX_FLAGS += -Os
CXX_FLAGS += -g1
CXX_FLAGS += -mcpu=cortex-m0
CXX_FLAGS += -mthumb

ASM_FLAGS += -x
ASM_FLAGS += assembler-with-cpp
ASM_FLAGS += -D__CORTEX_M0
ASM_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=2
ASM_FLAGS += -DCMSIS_VECTAB_VIRTUAL
ASM_FLAGS += -DARM_MATH_CM0
ASM_FLAGS += -D__MBED_CMSIS_RTOS_CM
ASM_FLAGS += -DCMSIS_VECTAB_VIRTUAL_HEADER_FILE="cmsis_nvic.h"
ASM_FLAGS += -D__CMSIS_RTOS
ASM_FLAGS += -I../$(CONFIG_DIR)/.
ASM_FLAGS += -I../$(LIB_DIR)/.
ASM_FLAGS += -I../$(LIB_DIR)/mbed
ASM_FLAGS += -I../$(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC
ASM_FLAGS += -I../$(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TARGET_STM
ASM_FLAGS += -I../$(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TARGET_STM/TARGET_STM32F0
ASM_FLAGS += -I../$(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F091RC
ASM_FLAGS += -I../$(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F091RC/device
ASM_FLAGS += -I../$(LIB_DIR)/mbed/TARGET_NUCLEO_F091RC/TARGET_STM/TARGET_STM32F0/device
ASM_FLAGS += -I../$(LIB_DIR)/mbed/drivers
ASM_FLAGS += -I../$(LIB_DIR)/mbed/hal
ASM_FLAGS += -I../$(LIB_DIR)/mbed/platform
ASM_FLAGS += -include
ASM_FLAGS += -x
ASM_FLAGS += assembler-with-cpp
ASM_FLAGS += -c
ASM_FLAGS += -Wall
ASM_FLAGS += -Wextra
ASM_FLAGS += -Wno-unused-parameter
ASM_FLAGS += -Wno-missing-field-initializers
ASM_FLAGS += -fmessage-length=0
ASM_FLAGS += -fno-exceptions
ASM_FLAGS += -fno-builtin
ASM_FLAGS += -ffunction-sections
ASM_FLAGS += -fdata-sections
ASM_FLAGS += -funsigned-char
ASM_FLAGS += -MMD
ASM_FLAGS += -fno-delete-null-pointer-checks
ASM_FLAGS += -fomit-frame-pointer
ASM_FLAGS += -Os
ASM_FLAGS += -g1
ASM_FLAGS += -mcpu=cortex-m0
ASM_FLAGS += -mthumb


LD_FLAGS :=-Wl,--gc-sections -Wl,--wrap,main -Wl,--wrap,_malloc_r -Wl,--wrap,_free_r -Wl,--wrap,_realloc_r -Wl,--wrap,_memalign_r -Wl,--wrap,_calloc_r -Wl,--wrap,exit -Wl,--wrap,atexit -Wl,-n -mcpu=cortex-m0 -mthumb 
LD_SYS_LIBS :=-Wl,--start-group -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys -lmbed -Wl,--end-group

# Tools and Flags
###############################################################################
# Rules

.PHONY: all lst size


all: $(PROJECT).bin $(PROJECT).hex size


.s.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
  
	@$(AS) -c $(ASM_FLAGS) -o $@ $<
  


.S.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
  
	@$(AS) -c $(ASM_FLAGS) -o $@ $<
  

.c.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CC) $(C_FLAGS) $(INCLUDE_PATHS) -o $@ $<

.cpp.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CPP) $(CXX_FLAGS) $(INCLUDE_PATHS) -o $@ $<


$(PROJECT).link_script.ld: $(LINKER_SCRIPT)
	@$(PREPROC) $< -o $@



$(PROJECT).elf: $(OBJECTS) $(SYS_OBJECTS) $(PROJECT).link_script.ld 
	+@echo "link: $(notdir $@)"
	@$(LD) $(LD_FLAGS) -T $(filter-out %.o, $^) $(LIBRARY_PATHS) --output $@ $(filter %.o, $^) $(LIBRARIES) $(LD_SYS_LIBS)


$(PROJECT).bin: $(PROJECT).elf
	$(ELF2BIN) -O binary $< $@
	+@echo "===== bin file ready to flash: $(OBJDIR)/$@ =====" 

$(PROJECT).hex: $(PROJECT).elf
	$(ELF2BIN) -O ihex $< $@


# Rules
###############################################################################
# Dependencies

DEPS = $(OBJECTS:.o=.d) $(SYS_OBJECTS:.o=.d)
-include $(DEPS)
endif

# Dependencies
###############################################################################
